language: generic

sudo: required

services:
    - docker

before_install:
    - docker build -t luisatjayacompany/docker-react-2 -f frontend/Dockerfile.dev ./frontend

script:
    - docker run -e CI=true luisatjayacompany/docker-react-2 npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react-lucho-2"
    env: "DockerReactLucho2-env"
    bucket_name: "elasticbeanstalk-us-east-2-774154012305"
    bucket_path: "docker-react-lucho-2"
    on:
        branch: master

    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY