language: generic

sudo: required

services:
    - docker

before_install:
    - docker build -t luisatjayacompany/docker-react -f Dockerfile.dev ./frontend

script:
    - docker run -e CI=true luisatjayacompany/docker-react npm run test